// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.4
// source: proto/game-data.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "game_data";

/** ===== COMMON ===== */
export interface Empty {
}

/** ===== MAP BASE ===== */
export interface MapBase {
  id: number;
  ten: string;
}

export interface GetAllMapResponse {
  maps: MapBase[];
}

export interface ThemMapRequest {
  ten: string;
}

export interface SuaMapRequest {
  id: number;
  ten: string;
}

export interface XoaMapRequest {
  id: number;
}

/** ===== NPC BASE ===== */
export interface NpcBase {
  id: number;
  ten: string;
  /** NGUOI, CAYDAU, RUONGDO, DUIGA */
  loai: string;
}

export interface GetAllNpcBaseResponse {
  npcs: NpcBase[];
}

export interface ThemNpcBaseRequest {
  ten: string;
  loai: string;
}

export interface SuaNpcBaseRequest {
  id: number;
  ten: string;
  loai: string;
}

export interface XoaNpcBaseRequest {
  id: number;
}

/** ===== NPC SPAWN ===== */
export interface NpcSpawn {
  id: number;
  npc_base_id: number;
  /** join từ npc_base để client khỏi query thêm */
  ten_npc: string;
  loai_npc: string;
  map_id: number;
  /** join từ map_base */
  ten_map: string;
  x: number;
  y: number;
  is_active: boolean;
}

export interface GetNpcTheoMapRequest {
  map_id: number;
}

export interface GetNpcTheoMapResponse {
  npcs: NpcSpawn[];
}

export interface ThemNpcSpawnRequest {
  npc_base_id: number;
  map_id: number;
  x: number;
  y: number;
  is_active: boolean;
}

export interface SuaNpcSpawnRequest {
  id: number;
  map_id: number;
  x: number;
  y: number;
  is_active: boolean;
}

export interface XoaNpcSpawnRequest {
  id: number;
}

export const GAME_DATA_PACKAGE_NAME = "game_data";

/** ===== SERVICE DEFINITION ===== */

export interface GameDataServiceClient {
  /** Map base */

  getAllMap(request: Empty, metadata?: Metadata): Observable<GetAllMapResponse>;

  themMap(request: ThemMapRequest, metadata?: Metadata): Observable<MapBase>;

  suaMap(request: SuaMapRequest, metadata?: Metadata): Observable<MapBase>;

  xoaMap(request: XoaMapRequest, metadata?: Metadata): Observable<Empty>;

  /** Npc base */

  getAllNpcBase(request: Empty, metadata?: Metadata): Observable<GetAllNpcBaseResponse>;

  themNpcBase(request: ThemNpcBaseRequest, metadata?: Metadata): Observable<NpcBase>;

  suaNpcBase(request: SuaNpcBaseRequest, metadata?: Metadata): Observable<NpcBase>;

  xoaNpcBase(request: XoaNpcBaseRequest, metadata?: Metadata): Observable<Empty>;

  /** Npc spawn */

  getNpcTheoMap(request: GetNpcTheoMapRequest, metadata?: Metadata): Observable<GetNpcTheoMapResponse>;

  themNpcSpawn(request: ThemNpcSpawnRequest, metadata?: Metadata): Observable<NpcSpawn>;

  suaNpcSpawn(request: SuaNpcSpawnRequest, metadata?: Metadata): Observable<NpcSpawn>;

  xoaNpcSpawn(request: XoaNpcSpawnRequest, metadata?: Metadata): Observable<Empty>;
}

/** ===== SERVICE DEFINITION ===== */

export interface GameDataServiceController {
  /** Map base */

  getAllMap(request: Empty, metadata?: Metadata): Observable<GetAllMapResponse>;

  themMap(request: ThemMapRequest, metadata?: Metadata): Observable<MapBase>;

  suaMap(request: SuaMapRequest, metadata?: Metadata): Observable<MapBase>;

  xoaMap(request: XoaMapRequest, metadata?: Metadata): Observable<Empty>;

  /** Npc base */

  getAllNpcBase(request: Empty, metadata?: Metadata): Observable<GetAllNpcBaseResponse>;

  themNpcBase(request: ThemNpcBaseRequest, metadata?: Metadata): Observable<NpcBase>;

  suaNpcBase(request: SuaNpcBaseRequest, metadata?: Metadata): Observable<NpcBase>;

  xoaNpcBase(request: XoaNpcBaseRequest, metadata?: Metadata): Observable<Empty>;

  /** Npc spawn */

  getNpcTheoMap(request: GetNpcTheoMapRequest, metadata?: Metadata): Observable<GetNpcTheoMapResponse>;

  themNpcSpawn(request: ThemNpcSpawnRequest, metadata?: Metadata): Observable<NpcSpawn>;

  suaNpcSpawn(request: SuaNpcSpawnRequest, metadata?: Metadata): Observable<NpcSpawn>;

  xoaNpcSpawn(request: XoaNpcSpawnRequest, metadata?: Metadata): Observable<Empty>;
}

export function GameDataServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getAllMap",
      "themMap",
      "suaMap",
      "xoaMap",
      "getAllNpcBase",
      "themNpcBase",
      "suaNpcBase",
      "xoaNpcBase",
      "getNpcTheoMap",
      "themNpcSpawn",
      "suaNpcSpawn",
      "xoaNpcSpawn",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("GameDataService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("GameDataService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const GAME_DATA_SERVICE_NAME = "GameDataService";
